database: all.bib

add:
  path: import 

check-files:
  format: csv

  ignore:
    - .git
    - .gitignore
    - .rsync-filter
    - all.bib
    - status.tsv
    - README
    - (0sort|event, slides|periodical|review|course/(ESD.S40|KTCP))/
    - book/.*/.*
    # For after general exams
    - JPSPGC .*
    - CA-ON .*

  filter:
    - field: ENTRYTYPE
      value: online
      sort: other

    - field: ENTRYTYPE
      value: proceedings
      sort: other

    - field: keywords
      value: x-pnk:correspondence
      sort: other

    - field: keywords
      value: x-pnk:database
      sort: other

    - field: keywords
      value: x-pnk:hardcopy
      sort: other

    - field: keywords
      value: x-pnk:later
      sort: other

    - field: keywords
      value: x-pnk:no-file
      sort: other

    - field: keywords
      value: x-pnk:own-work
      sort: other

queue:
  include: x-pnk:queue-(?P<priority>\w+)
