database: all.bib

import:
  path: 0sort/bib

check_files:
  format: csv

  ignore:
    - .git
    - .gitignore
    - .rsync-filter
    - all.*
    - biblatex-dm.cfg
    - status.tsv
    - README
    - (0sort|abstracts|event, slides|periodical|review)/
    - course/*/
    # Chapters of books
    - book/.*/.*
    # For after general exams
    - JPSPGC .*
    - CA-ON .*

  filter:
    - field: ENTRYTYPE
      value: online
      sort: other

    - field: ENTRYTYPE
      value: proceedings
      sort: other

    - field: keywords
      value: x-pnk:correspondence
      sort: other

    - field: keywords
      value: x-pnk:database
      sort: other

    - field: keywords
      value: x-pnk:hardcopy
      sort: other

    - field: keywords
      value: x-pnk:later
      sort: other

    - field: keywords
      value: x-pnk:no-file
      sort: other

    - field: keywords
      value: x-pnk:own-work
      sort: other

queue:
  include: x-pnk:queue-(?P<priority>\w+)
